### ISSUE TITLE
Cannot Get data

### ISSUE THREAD

**Issue by mjwang1010** [khufkens/modis-land-product-subset#1]
Hi, Hufkens

I tried the fourth function in my terminal, but it got no data in my file at last. The screen just shows:
"
###### 
###### ##### CALCULATING MODIS DAAC SUBSETS

 Header flag is set to: T
 --> Evaluating: US-Ton
 --> Latitude / Longitude: 38.4316 / -120.966

Subroutine _call redefined at (eval 123) line 74.
Subroutine myServiceHandlerService::want_som redefined at (eval 123) line 119.
Subroutine AUTOLOAD redefined at (eval 123) line 136.
Subroutine myServiceHandlerService::getsubset redefined at (eval 123) line 134.
Subroutine myServiceHandlerService::getbands redefined at (eval 123) line 134.
Subroutine myServiceHandlerService::getdates redefined at (eval 123) line 134.
Subroutine myServiceHandlerService::getsubsetorder redefined at (eval 123) line 134.
Subroutine myServiceHandlerService::getproducts redefined at (eval 123) line 134.
Subroutine _call redefined at (eval 134) line 74.
Subroutine myServiceHandlerService::want_som redefined at (eval 134) line 119.
Subroutine AUTOLOAD redefined at (eval 134) line 136.
Subroutine myServiceHandlerService::getsubset redefined at (eval 134) line 134.
Subroutine myServiceHandlerService::getbands redefined at (eval 134) line 134.
Subroutine myServiceHandlerService::getdates redefined at (eval 134) line 134.
Subroutine myServiceHandlerService::getsubsetorder redefined at (eval 134) line 134.
Subroutine myServiceHandlerService::getproducts redefined at (eval 134) line 134.
Subroutine _call redefined at (eval 141) line 74.
Subroutine myServiceHandlerService::want_som redefined at (eval 141) line 119.
Subroutine AUTOLOAD redefined at (eval 141) line 136.
Subroutine myServiceHandlerService::getbands redefined at (eval 141) line 134.
Subroutine myServiceHandlerService::getsubset redefined at (eval 141) line 134.
Subroutine myServiceHandlerService::getproducts redefined at (eval 141) line 134.
Subroutine myServiceHandlerService::getsubsetorder redefined at (eval 141) line 134.
Subroutine myServiceHandlerService::getdates redefined at (eval 141) line 134.
...
"
sort of lines like those above until the end " --> 100 % Complete!". I'm not sure what those are. Could you figure it out? Thanks!

My OS: Mac OS X EI Capitan
SOAP lite is the newest, I think

**Comment by khufkens** [comment]
The API dumps some garbage to the command line which I don't trap. The routine works fine on my system (OSX El Capitan / Linux), returning normal values for your location (land cover product). Check your library first I would say and if the product is truly available.

**Comment by khufkens** [comment]
btw. unless you are tied to perl in some other way I suggest to use MODISTools in R. It provides the same functionality and if you are doing analysis in R anyway it's far more convenient (although the data structure is a bit weird at times).

**Comment by mjwang1010** [comment]
Yeah, I just tried that tool and the downloading speed was a little bit slow, I think. Also, I'm trying to figure out how to download multiple sites by that. Anyway, its summary function seems have more features. I should try more later. 
Thanks!
